### ISSUE TITLE
Citação em trabalho de pesquisa 

### ISSUE THREAD

**Issue by awillsousa** [rafaelanchieta/essay#1]
Olá! Gostaria de utilizar a sua base de redações em uma pesquisa que estou desenvolvendo. Inclusive, estive trabalhando na montagem de uma base semelhante, com arquivos de redações do portal Brasil Escola.  Por favor, você poderia me passar como devo fazer a citação de autoria da sua base de redações?

**Comment by rafaelanchieta** [comment]
Oi Willian Sousa.

O artigo está em processo de avaliação em uma conferência. Vamos disponibilizar uma versão pré-print no Arxiv para você poder citar o trabalho.

**Comment by awillsousa** [comment]
Obrigado!

**Comment by rafaelanchieta** [comment]
Oi Willian.
Link da versão pré-print: http://arxiv.org/abs/2105.09081

**Comment by awillsousa** [comment]
Muito obrigado!
Será de grande ajuda.
